language: python
python: 2.7
env:
  - TOX_ENV=py27-unit
  - TOX_ENV=py27-lint
  - TOX_ENV=py27-func
  - TOX_ENV=pypy-unit
  - TOX_ENV=pypy-func
  - TOX_ENV=docs
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
